title:            天际的技术分享
description:      "Hi，我是天际，是一个软件工程师，欢迎来到我的博客。"

url: https://skytools.cn
menu:
  - title: 'Categories'
    url: '/categories.html'
  - title: 'About'
    url: '/about'
  - title: 'RSS'
    url: '/feed.xml'

timezone:    Africa/El_Aaiun
locale:      zh_CN
lang:      zh-cmn-Hans
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

permalink:   /:year-:month-:day/:title.html
assetUrl: //skytools.cn/images/
defaultImage: 

#google_analytics: 
#baidu_verify: 
#google_verify: 

paginate: 10
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true

showBuyCoffee: true
payImage: //skytools.cn/images/buymecoffee.JPG

include: [".htaccess"]
exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE", "package.json","node_modules"]
#gems:


plugins:
  - jekyll-paginate
  - jekyll-pdf-embed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
