title:            eric yang
description:      "Hi，我是 eric yang，是一个软件工程师，欢迎来到我的博客。"

url: https://blog.fire-eyes.com
menu:
  - title: 'Categories'
    url: '/categories.html'
  - title: 'About'
    url: '/about'
  - title: 'RSS'
    url: '/feed.xml'

timezone:    Africa/El_Aaiun
locale:      zh_CN
lang:      zh-cmn-Hans
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

permalink:   /:year-:month-:day/:title.html
assetUrl: //blog.fire-eyes.com/images/
defaultImage: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==

#google_analytics: 
#baidu_verify: 
#google_verify: 

paginate: 10
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true

showBuyCoffee: true
payImage: //gw.alipayobjects.com/zos/k/vb/1.png

include: [".htaccess"]
exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE", "package.json","node_modules"]
#gems:


plugins:
  - jekyll-paginate
  - jekyll-pdf-embed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
